#from https://github.com/discospiff/MyPlantDiary32/blob/master/.circleci/config.yml
version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2025.10
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "OTAMS_project_with_CircleCI/build.gradle" }}-{{ checksum "OTAMS_project_with_CircleCI/app/build.gradle" }}
      - run:
          name: chmod permissions
          command: cd OTAMS_project_with_CircleCI && chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: cd OTAMS_project_with_CircleCI && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/OTAMS_project_with_CircleCI/.gradle
          key: jars-{{ checksum "OTAMS_project_with_CircleCI/build.gradle" }}-{{ checksum "OTAMS_project_with_CircleCI/app/build.gradle" }}
      - run:
          name: Run Tests
          command: cd OTAMS_project_with_CircleCI && ./gradlew lint test
      - run:
          name: Start Emulator
          command: |
            sdkmanager "system-images;android-33;google_apis;x86_64"
            echo "no" | avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --force
            $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-snapshot &
            adb wait-for-device
            adb shell input keyevent 82  # unlock screen
      - run:
          name: Run Instrumented Tests
          command: cd OTAMS_project_with_CircleCI && ./gradlew connectedAndroidTest            
      - store_artifacts:
          path: OTAMS_project_with_CircleCI/app/build/reports
          destination: reports
      - store_test_results:
          path: OTAMS_project_with_CircleCI/app/build/test-results
