#from https://github.com/discospiff/MyPlantDiary32/blob/master/.circleci/config.yml
version: 2.1
jobs:
  build:
    working_directory: ~/project/OTAMS_project_with_CircleCI
    docker:
      - image: circleci/android:api-24
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: pwd
      - run: ls
