#from https://github.com/discospiff/MyPlantDiary32/blob/master/.circleci/config.yml
version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-24
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "OTAMS_project_with_CircleCI/build.gradle" }}-{{ checksum "OTAMS_project_with_CircleCI/app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./OTAMS_project_with_CircleCI/gradlew
      - run:
          name: Download Dependencies
          command: ./OTAMS_project_with_CircleCI/gradlew androidDependencies
      - save_cache:
          paths:
            - ~/OTAMS_project_with_CircleCI/.gradle
          key: jars-{{ checksum "OTAMS_project_with_CircleCI/build.gradle" }}-{{ checksum "OTAMS_project_with_CircleCI/app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./OTAMS_project_with_CircleCI/gradlew lint test
      - store_artifacts:
          path: OTAMS_project_with_CircleCI/app/build/reports
          destination: reports
      - store_test_results:
          path: OTAMS_project_with_CircleCI/app/build/test-results
